### ISSUE TITLE
response structure

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/sqldep-analyzer#1]
forked from https://github.com/keboola/transformation-bundle/issues/94

jak nad tím přemejšlím, tak možná bude lepší odpověď sqldepu přemapovat a poslat univerzální hlášku, kde by se tohle mohlo injectnout (a do sqldepu vůbec neposílat). to by mohlo bejt i kvůli nějaký budoucí zpětný  kompatibilitě lepší.

takže místo

```json
[
  {
    "status_code": "ANALYZE_ERROR",
    "status_desc": "Validation issue: table public.in_table was used at line 1 column 43. However table DDL is missing.",
    "id": 2,
    "name": "368746359.query.2"
  }
]
```
by to mohlo poslat něco jako (hodně od boku)
```json
[
  {
    "bucket": "mytransformationbucket",
    "transformation": "mytransformation",
    "object": {
        "type": "table",
        "id": "mytable"
    },
    "message": "Validation issue: table public.in_table was used at line 1 column 43. However table DDL is missing.",
  },
  {
    "bucket": "mytransformationbucket",
    "transformation": "mytransformation2",
    "object": {
        "type": "query",
        "id": 2, 
    },
    "message": "Validation issue: table public.in_table was used at line 1 column 43. However table DDL is missing.",
  }  
]
```

obalovací strukturu neřeším

**Comment by JakubMatejka** [comment]
Teď nevím, jestli to chápu dobře:
1. odpovědi z Sqldepu přeformátovat cca do tý podoby `[{ bucket: '', transformation: '', object: {}, message }]`
2. při neexistujících mapovaných tabulkách vůbec neposílat do SQLdepu

?

**Comment by ondrejhlavacek** [comment]
1. ano, jestli ti to taky dává smysl
2. taky nevím, co myslíš? pokud se to do sqldepu
  a) nepošle, uživatel dostane jen jednu chybu na začátku řetězce a nic dál mu to neřekne (to může bejt hromada chyb závisejících na té úvodní chybě)
  b) pošle, uživatel může dostat sérii závislejch chyb, ale zároveň může snadno odhalit nějaký laciný překlepy, nebo dokonce může bejt absence tabulky chtěná

u 2 bych asi osobně volil b), lintery, testy, statický analýzy kódu apod se taky nezastaví u první chyby, ale jedou dál a podaj full report

**Comment by JakubMatejka** [comment]
Tak asi jo, pokud to bude lepší pro ui. Pustím se do toho.

**Comment by JakubMatejka** [comment]
Už to budu mít za chvíli pohromadě. Validace bez chyb tedy vrátí jen `[]`, validace s chybama (`https://yl2jrv15aj.execute-api.eu-west-1.amazonaws.com/dev/368746352/368746390/validate`) pak bude cca:
```json
[
  {
    "transformation": "368746390",
    "object": {
      "type": "table",
      "id": "out.c-sqldep-validation.out_users"
    },
    "message": "Table out.c-sqldep-validation.out_users defined in output mapping of transformation 368746390 does not exist in Storage."
  },
  {
    "transformation": "368746390",
    "object": {
      "type": "table",
      "id": "out.c-sqldep-validation.doesnotexist"
    },
    "message": "Table out.c-sqldep-validation.doesnotexist defined in output mapping of transformation 368746390 does not exist in Storage."
  },
  {
    "transformation": "368746359",
    "object": {
      "type": "query",
      "id": "2"
    },
    "message": "Validation issue: table public.in_table was used at line 1 column 43. However table DDL is missing."
  },
  {
    "transformation": "368746390",
    "object": {
      "type": "query",
      "id": "1"
    },
    "message": "Validation issue: table public.in_table was used at line 1 column 43. However table DDL is missing."
  },
  {
    "transformation": "368746390",
    "object": {
      "type": "query",
      "id": "2"
    },
    "message": "Validation issue: table public.aabb was used at line 1 column 42. However table DDL is missing."
  }
]
```

**Comment by JakubMatejka** [comment]
Fixed by https://github.com/keboola/sqldep-analyzer/releases/tag/2.0.0

**Comment by ondrejhlavacek** [comment]
šlape, díky!
