### ISSUE TITLE
Duplicite Output Mapping (Table Does Not Exist In Storage)

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/sqldep-analyzer#10]
https://connection.keboola.com/admin/projects/232/transformations/bucket/368746352/transformation/370687520

2d) z #5 

Šlo by nějak ověřit, že struktura sedí? Možná by šlo udělat dotaz typu

```
SELECT * FROM `table1`
UNION
SELECT * FROM `table2`
```
a SQLdep by mohl vyhodit chybu, kterou by API přechroustalo do nějaký uživatelsky srozumitelný hlášky, třeba

```
    {
        "transformation": "1",
        "object": {
            "type": "output",
            "id": "table2"
        },
        "message": "Table1 and table2 do not match in output mapping to table `out.c-data.table`"
    }
```

**Comment by JakubMatejka** [comment]
Takže jestli to chápu dobře mám dát dohromady všechny output mappingy, nějak z nich dostat ty, který jsou namapovaný na stejný tabulky, potom na nich udělat ty uniony a přidat je k těm queries co jdou do sqldepu? 

Ok no, akorát mi trochu přijde, že tady ty poslední změny moc s sqldepem nesouvisí a je to spíš o nějaký validaci konfigurace, to jsme tu komponentu asi měli pojmenovat trochu jinak. Škoda, že jsem tohle všechno nevěděl na začátku. ;o)

**Comment by ondrejhlavacek** [comment]
To nevěděl asi nikdo :-(. Taky to z toho můžeme vyhodit a fakt validovat jen to, co řeší SQLdep a zbytek jinak/jinde?

**Comment by JakubMatejka** [comment]
Jasně, to já si jen tak povzdechl. 😃 Hmm, tak to nějak dáme dohromady a pak to když tak upravíme/rozdělíme.

**Comment by JakubMatejka** [comment]
Tahle validace ale output mapping nebude řešit, protože ta namapovaná tabulka ve Storagi neexistuje.

**Comment by JakubMatejka** [comment]
Tý jo, ale názvy těch nekonzistentních tabulek tam asi nedostanu. Nestačilo by napsat do chyby, že mappingy snažící se o zápis do Storage tabulky s id xxx nejsou konzistentní?

**Comment by ondrejhlavacek** [comment]
https://github.com/keboola/sqldep-analyzer/issues/10#issuecomment-376565318

Napadá mě, jak to udělat, ale už to radši nechám bejt. Odložím pro budoucí pokolení :-)

Pokud by SQLdep dokázal vyhodit chybu, když se udělá dvakrát CREATE TABLE se stejným názvem a rozdílnou definicí (cca jak to bylo tady https://github.com/keboola/sqldep-analyzer/issues/2#issuecomment-375221749) tak by to asi šlo.

**Comment by ondrejhlavacek** [comment]
https://github.com/keboola/sqldep-analyzer/issues/10#issuecomment-376574583

Nebudem na ně v UI pak moc udělat link (on ten link je stejně divnej, protože bychom měli říct kolik takovejch tabulek ne a nemusej bejt třeba jenom 2, ale víc...), takže asi tak. Klidně bych ten parametr `id` vynechal a vlastně se možná může vynechat i link na transformaci, protože je tam stejná situace? Ha, tak teď fakt nevím :-(

**Comment by JakubMatejka** [comment]
Mě tak napadlo vyjmenovat všechny ty tabulky do `name` tý query co se posílá do Sqldepu, ale to je takový trošku hloupý. Hmm, ale tak mohl bych těm mappingům dát nějaký idčka a někam vedle si poznačit jejich seznam a uložit k nim pole s názvama tabulek.

CREATE TABLE? Ale output mapping dělá SELECT (vyjmenuje sloupce z mapované tabulky ve Storagi a do FROM dá název tabulky v transformaci (tj. `source`)).

Na mý testovací konfiguraci teď parametry a výstup Sqldepu vypadají takto:
![cloudwatch management console 2018-03-27 18-02-15](https://user-images.githubusercontent.com/215660/37979631-5bc06e98-31e9-11e8-8fe3-25c3ca44d961.png)

**Comment by ondrejhlavacek** [comment]
No s tím `CREATE TABLE` jsem právě říkal, že to radši odložím dalším generacím :-) Protože by to mělo bejt asi

```
CREATE TABLE __tmp_out1 AS SELECT * FROM user;
CREATE TABLE __tmp_out1 AS SELECT * FROM user2;
```
(Tady to zařve, pokud  jsou `user` a `user2` rozdílný)

A v případě, že tabulka ve Storage existuje, tak dohodit
```
SELECT {columns dle Storage} FROM  __tmp_out1;
```

**Comment by ondrejhlavacek** [comment]
https://github.com/keboola/sqldep-analyzer/issues/10#issuecomment-376581128

Udržovat si data bokem a párovat to přes nějaký vymyšlený IDčka je rozumný. Jak moc velkej oser to je?

**Comment by JakubMatejka** [comment]
Už to skoro mám, spíš se tím ten kód docela zamotá, ale co naděláme. ;o) Může ta chyba z API vypadat tak nějak?
```json
{
    "transformation": "372521165",
    "object": {
      "type": "output_consistency",
      "id": ["users1", "users2"]
    },
    "message": "Tables users1 and users2 do not match in output mapping to table out.c-main.users."
  }
```

**Comment by ondrejhlavacek** [comment]
Co kdyby to bylo roztržený do dvou error messagí? Protože `users1` a `users2` můžou bejt i v jiný transformaci.

**Comment by JakubMatejka** [comment]
Takže takhle?
![sqldep analyzer 2018-03-27 19-02-34](https://user-images.githubusercontent.com/215660/37982647-71296bd8-31f1-11e8-8fa3-25710b4c6b61.png)

**Comment by JakubMatejka** [comment]
(ještě bych tu zprávu upravil na `Table ${key} does not match output mapping of table ${tableId}.`)

**Comment by ondrejhlavacek** [comment]
nebo `Output mapping of table ${key} does not match talbe ${tableId} in Storage.`?

**Comment by JakubMatejka** [comment]
jj. upravil jsem to a je to tam:
![sqldep analyzer 2018-03-28 10-28-54](https://user-images.githubusercontent.com/215660/38017623-d5ca7650-3272-11e8-9528-e00d788c4054.png)
Ještě se dívám na to složení API url (`https://sqldep.keboola.com/353453003/372521165/validate`), je to ok? Na začátku jsem to tam jen narychlo hodil, ale pak už jsem se nad tím samozřejmě zapomněl zamyslet. ;o)

**Comment by ondrejhlavacek** [comment]
Možná dát ty dva číselný argumenty do parametrů?

`https://sqldep.keboola.com/validate?configId=#&rowId=#`? (`configId` a `rowId` bude trochu víc future-proof)

**Comment by JakubMatejka** [comment]
Udělal jsem to tak

**Comment by ondrejhlavacek** [comment]
Tak tady mi to nevalí, co dělám blbě?

https://connection.keboola.com/admin/projects/232/transformations/bucket/368746352/transformation/370687520

**Comment by JakubMatejka** [comment]
No jo, ale to je tím, že ty out tabulky neexistují.

**Comment by JakubMatejka** [comment]
(takže se nemůžou sestavit ty jejich selecty, co se pak posílají do Sqldepu)

**Comment by ondrejhlavacek** [comment]
Jasně, tomu rozumím. Nevím, jestli to není nějaký edge case, ale šlo by to vyřešit tím, že jeden output mapping udělá `CREATE TABLE "outputmapping" AS SELECT * FROM "table1";` a druhej třeba `INSERT INTO "outputmapping" SELECT * FROM "table2";`. Ale můžem to taky asi vynechat, jen bych to tu nechal otevřený, kdyby si na to někdo stěžoval.

**Comment by ondrejhlavacek** [comment]
Hm, tak tohle je dobrej point, tenhle use case mě nenapadl. Tohle bychom měli nějak namockovat a vyřešit.

**Comment by ondrejhlavacek** [comment]
Narazili jsme na to znovu.

![image](https://user-images.githubusercontent.com/497675/39622005-f6fec250-4f90-11e8-89b1-e9deb0b02ca7.png)

vygeneruje to takovehle dotaz

```
{
    "queries": [
        {
            "id": "388395291.query.1",
            "executionUser": "public",
            "name": "388395291.query.1",
            "sourceCode": "create table test (tm timestamp);"
        },
        {
            "id": "388395291.query.2",
            "executionUser": "public",
            "name": "388395291.query.2",
            "sourceCode": "insert into test values(current_date());"
        }
    ],
    "errors": []
}
```

**Comment by JakubMatejka** [comment]
@ondrejhlavacek Takže jestli to dobře chápu: mám projít output mappingy, zkontrolovat jestli tabulky existují ve storagi a pokud ne, tak do Sqldepu přidat `SELECT * FROM "doesnotexist"`. (To je všechno, tady ten insert už k tomu aktuální není: https://github.com/keboola/sqldep-analyzer/issues/10#issuecomment-380014565?)

**Comment by ondrejhlavacek** [comment]
tak `UNION` nepomůže, nematchuje názvy sloupců, ale jen jejich počet

```
CREATE TABLE "test1" ("col1" NUMBER);
INSERT INTO "test1" VALUES (1);
CREATE TABLE "test2" ("col1" NUMBER);
INSERT INTO "test1" VALUES (2);
CREATE TABLE "test3" ("col2" VARCHAR);
INSERT INTO "test1" VALUES ('3');

SELECT * FROM "test1" UNION SELECT * FROM "test2" UNION SELECT * FROM "test3";
```

![image](https://user-images.githubusercontent.com/497675/40228343-508afc98-5a91-11e8-9986-13bafb07b3d7.png)

**Comment by ondrejhlavacek** [comment]
s insertem to bude teda podobný! vydetekuje to jen změny v počtech sloupců, nikoliv v názvech.

**Comment by ondrejhlavacek** [comment]
zkusím ještě promyslet, jestli by na to nebyl nějakej trik

**Comment by odinuv** [comment]
a transfromace to pri provadeni toho OM nezachyti?

**Comment by ondrejhlavacek** [comment]
jasně, ta to zachytí, ale pointa je odchytit co nejvíc bugů bez spuštění

**Comment by ondrejhlavacek** [comment]
Dospěli jsme k tomu, že to asi není možný. Dopsal bych do modalu validace, že output mapping neexistujících tabulek se nekontroluje a že případné chyby se projeví až při exekuci.
