### ISSUE TITLE
Validation messages

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/sqldep-analyzer#13]
Procházím ještě jednou všechny hlášky, co se zobrazují uživateli a myslím si, že bude potřeba je upravit. Samotné SQL transformace je v pohodě (tam bude stačit odstranit `Validation issue: `, protože to je jasný z kontextu), ale ty ručně dodělávané SQLka (input/output mappingy) dostávají do UI hlášky, které nedávají smysl - nemají vazbu na nic, co by uživatel viděl.

Příklad:

Mám v transformaci dva input mappingy do stejný tabulky. Současná hláška je `Validation issue: Table users at line 1 column 14 already exists`. Z toho by stačilo úplně udělat `Table users already exists` (a pokud analyzer ví, že je to z input mappingu, tak třeba `Table users already used in input mapping`.

Napadá tě, jak nejlíp na to? Klidně se do toho pustím, je to taková debilní mravenčí práce.

**Comment by ondrejhlavacek** [comment]
https://keboola.slack.com/archives/C7UKEFVJR/p1523351434000363

**Comment by ondrejhlavacek** [comment]
Tak tady je seznam hlášek sqldepu
```
MonadAnalyzer.SyntaxFailure = Unable to proceed with syntax parsing at line {0} column {1}.
MonadAnalyzer.MissingDefinition = Validation issue: {0} was used at line {1} column {2}. However table DDL is missing.
MonadAnalyzer.TableExists = Validation issue: Table {0} at line {1} column {2} already exists.
MonadAnalyzer.InvalidColumn = Unknown name of the target column in INSERT INTO {0} at line {1}, column {2}. Please provide table structure.
MonadAnalyzer.ColumnTableNotUnique = Please adjust your SQL and provide table name/alias for ambiguous column "{0}" at line {1}, column {2}.
MonadAnalyzer.NoFromItem = Problem with the source table for column "{0}" at line {1}, column {2}.
MonadAnalyzer.JavaLangError = Unknown error encountered
MonadAnalyzer.NoColumnName = SELECT statement contains expression with no alias assigned at line {0}, column {1}.
MonadAnalyzer.InsertColumnNumberMismatch = Inserting {0} values into {1} columns at line {2}, column {3}.
MonadAnalyzer.ExchangeMismatch = ALTER TABLE EXCHANGE PARTITION query requires both tables {0} (size {2}) and {1} (size {3}) to exist and match the column count; line {4}, column {5}.
MonadAnalyzer.ColumnNumberMismatch = Required number of columns not returned by the SELECT statement at line {0}, column {1}.
MonadAnalyzer.OutputClauseColumnNumberMismatch = Number of source columns ({0}) must be equal to number of target columns ({1}) in the OUTPUT clause at line {2}, column {3}
MonadAnalyzer.NoWildcardMatch = No columns selected by wildcard at line {0}, column {1} from table(s) {2}. Please provide table structure.
MonadAnalyzer.ColumnNameNotUnique = Column name "{0}" specified more than once in CREATE query at line {1}, column {2}.
MonadAnalyzer.UndefinedFunction = Missing definition of the function {0} called at line {1}, column {2}.
```
Bude potřeba v nějakejch situacích si to přemapovat zpět a vyhlásit něco jiného. 

@JakubMatejka mám se do toho nějak pustit? Dal bys mi nějakou drobnou navigaci, jak na to? Nebo se toho chceš ujmout ty?

**Comment by ondrejhlavacek** [comment]
+ ještě

`Problem with the source table for column "{0}" at line {1}, column {2}.` zmenime na `Cannot find parent table for column "{0}" at line {1}, column {2}.` OK? (edited)

**Comment by JakubMatejka** [comment]
Při nejmenším budeš mít lepší představu o tom jak by ty zprávy měly vypadat. Kam to dát, hm, asi někam sem: https://github.com/keboola/sqldep-analyzer/blob/master/src/app/Validate.js#L47 Ale jestli chceš, tak můžeš dát dohromady ty zprávy a já to tam pak zapojím. 

BTW. když už máme ten `configRow` v parametrech, tak bysme mohli přejmenovat i ten `transformation` na výstupu? (https://github.com/keboola/sqldep-analyzer/blob/master/src/app/Validate.js#L57)

**Comment by ondrejhlavacek** [comment]
`transformationId` => `rowId` 
Jo, to by bylo kvůli konzistenci asi o něco lepší.

Koukám na funkce `parseSqldepMessages` a `parseStorageErrors`, ty nejsou samostatně nikde testovaný, že? Začal bych teda vytvořením testů a ty bych pak začal rozšiřovat. Přemapování těch hlášek bych asi hodil do vlastní funkce, ať se to líp testuje, odpovědi sqldepu bych mockoval (ideáně bych to teda měl bez interakce se sqldepem).

Akorát se mi to nedaří rozjet lokálně, build mi hlásí

```
Serverless plugin "@keboola/serverless-papertrail-logging" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.
```

**Comment by JakubMatejka** [comment]
ok, pardon. protáhl se mi oběd. Doufám, že to moc nebolelo. ;o) (chybí něco v readme?)

**Comment by ondrejhlavacek** [comment]
Fixed by #14
