### ISSUE TITLE
invalid table structure in output mapping

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/sqldep-analyzer#2]
forked from https://github.com/keboola/transformation-bundle/issues/94

A ještě jednu věc jsem objevil - https://connection.keboola.com/admin/projects/232/transformations/bucket/368746352/transformation/369630788

Transformace má jeden vstup, jeden výstup (tabulka v DB je stejně pojmenovaná), ale ve storage jsou ty tabulky rozdílný. Output mapping by měl pro SQLdep vygenerovat SELECT statement, ve kterým by byly sloupce z tabulky ve Storage a FROM je source tabulka v output mappingu.

**Comment by JakubMatejka** [comment]
é, cože? ;o) Momentálně to vygeneruje tohle:
![cloudwatch management console 2018-03-21 12-02-55](https://user-images.githubusercontent.com/215660/37706447-d6e3099e-2cff-11e8-8397-c0e4ec692898.png)

**Comment by ondrejhlavacek** [comment]
@JakubMatejka a to že to vytvoří 2 tabulky s jinou definicí ničemu nevadí?

output mapping jsem původně zamejšlel dělat pomocí selectu. tj. v tomhle případě by to dělalo následující

  1) input mapping tabulky `users` => definice jak je teď
  2) output mapping tabulky `users` do `out.c-users.users` pomocí `SELECT {columns from out.c-users.users} FROM users`

2 musí spadnout, protože sloupce v `out.c-users.users` nesedí se sloupcema tabulky `users` v transformaci.

**Comment by JakubMatejka** [comment]
Áha, už tomu rozumím. ;o)

**Comment by JakubMatejka** [comment]
Takže takhle? 
```
[{
    id: '369630788.input.in.c-bug-869.users',
    executionUser: 'public',
    name: '369630788.input.in.c-bug-869.users',
    sourceCode: 'sqldep-dbdef: "table","public","users","id","VARCHAR NOT NULL"; 
        sqldep-dbdef: "table","public","users","created_at","VARCHAR NOT NULL"; 
        sqldep-dbdef: "table","public","users","updated_at","VARCHAR NOT NULL"; 
        sqldep-dbdef: "table","public","users","sign_in_count","VARCHAR NOT NULL"; 
        sqldep-dbdef: "table","public","users","current_sign_in_at","VARCHAR NOT NULL"; 
        sqldep-dbdef: "table","public","users","last_sign_in_at","VARCHAR NOT NULL"; 
        sqldep-dbdef: "table","public","users","seen_onboarding","VARCHAR NOT NULL"; 
        sqldep-dbdef: "table","public","users","unseen_onboarding_steps","VARCHAR NOT NULL"; 
        sqldep-dbdef: "table","public","users","name","VARCHAR NOT NULL"; 
        sqldep-dbdef: "table","public","users","email","VARCHAR NOT NULL"; '
},
{
    id: '369630788.output.out.c-users.users',
    executionUser: 'public',
    name: '369630788.output.out.c-users.users',
    sourceCode: 'CREATE TABLE `out.c-users.users` AS SELECT `email`, `firstname`, `lastname`, `ssoprovider`, `filters`, `active`, `pid`, `writerid` FROM `users`;'
}]
```

Akorát, že mi to failuje na `Unable to proceed with syntax parsing at line 1 column 14.\n\nCREATE TABLE `out.c-users.users` AS SELECT `email`, `firstname`, `lastname`, `ssoprovider`, `filters`, `active`, `pid`, `writerid` FROM `users`;` Tj. na tom escapu názvu tabulky. Jenže když ho tam nedám, tak to failuje na pomlčce. Nevíš co s tím?

**Comment by ondrejhlavacek** [comment]
Stačí select a nemusí tam bejt id tabulky.

**Comment by JakubMatejka** [comment]
To jako do Sqldepu posílat jenom takhle?
```
{ id: '369630788.output.out.c-users.users',
executionUser: 'public',
name: '369630788.output.out.c-users.users',
sourceCode: 'SELECT `email`, `firstname`, `lastname`, `ssoprovider`, `filters`, `active`, `pid`, `writerid` FROM `users`;' }
```
Akorát že to zase failuje na tý zpětný uvozovce, tak escapovat nemám? (Jestli se koukám dobře, tak do teď se taky neescapují: https://github.com/keboola/transformation-bundle/blob/master/library/Keboola/Transformation/SqlDep.php#L100 ale nevím jestli je to úplně ok)

**Comment by ondrejhlavacek** [comment]
Snowflake ani Redshiftu backitcky nepoužívají

On Mar 22, 2018 5:00 PM, "Jakub Matějka" <notifications@github.com> wrote:

To jako do Sqldepu posílat jenom takhle?

{ id: '369630788.output.out.c-users.users',
executionUser: 'public',
name: '369630788.output.out.c-users.users',
sourceCode: 'SELECT `email`, `firstname`, `lastname`, `ssoprovider`,
`filters`, `active`, `pid`, `writerid` FROM `users`;' }

Akorát že to zase failuje na tý zpětný uvozovce, tak escapovat nemám?
(Jestli se koukám dobře, tak do teď se taky neescapují:
https://github.com/keboola/transformation-bundle/blob/
master/library/Keboola/Transformation/SqlDep.php#L100 ale nevím jestli je
to úplně ok)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/keboola/sqldep-analyzer/issues/2#issuecomment-375359851>,
or mute the thread
