### ISSUE TITLE
Validator is not case sensitive

### ISSUE THREAD

**Issue by Halama** [keboola/sqldep-analyzer#20]
Následující SQL transformace skonší chybou ale validace říká že je vše ok:
```
create table "pokus" (tm timestamp);
insert into pokus values(current_date());
```
https://connection.keboola.com/admin/projects/4088/transformations/bucket/381746322/transformation/381746832

Případně asi častější případ kombinace IM/OM a SQL.
V OM `pokus -> out.c-neco.pokus` a sql
```
create table pokus (tm timestamp);
insert into pokus values(current_date());
```
Tohle při spuštění končí chybou, validátor ale nezařve.
https://connection.keboola.com/admin/projects/4088/transformations/bucket/381746322/transformation/381748009

**Comment by ondrejhlavacek** [comment]
Ten první případ je podle mě dost běžnej a na Snowflake to potrápí dost uživatelů. Budem to muset loopnout přes SQLdep.

**Comment by Halama** [comment]
jo to je imho to na čem člověk nejčastěji poprvé failne a ta validace by mu s tím měla pomoct

**Comment by Halama** [comment]
teda spíš  ten druhej případ. Nebo případ kdy máš v Im lower case tabulku a vtransformaci nequotuješ, to je asi nejčastější.

**Comment by ondrejhlavacek** [comment]
https://gist.github.com/ondrejhlavacek/1646f31289e90cd77a7ff3ab7c1c0926
https://keboola.slack.com/archives/C7UKEFVJR/p1524124696000341

**Comment by ondrejhlavacek** [comment]
no, takže vlastně oboje. dík moc za check, tohle mě nenapadlo!

**Comment by ondrejhlavacek** [comment]
fixnuto!
https://keboola.slack.com/archives/C7UKEFVJR/p1524467980000392
