### ISSUE TITLE
Input mapping columns quoting

### ISSUE THREAD

**Issue by Halama** [keboola/sqldep-analyzer#21]
Vypadá to že jmená sloupců nejsou quotovaná při validaci input mappingu. Potom to končí dost podivnou validační chybou i pro validní transformace.

```
Unable to proceed with syntax parsing at line 1 column 22. CREATE TABLE "test" (21_03_2018_57 VARCHAR NOT NULL) ^
```

![image](https://user-images.githubusercontent.com/903531/38975086-cdce42c4-43ac-11e8-92f5-1bf5f5b2cf93.png)

https://connection.keboola.com/admin/projects/4088/transformations/bucket/381747904/transformation/381747919

**Comment by JakubMatejka** [comment]
Já je samozřejmě quotoval, ale Sqldepu se to nelíbilo a @ondrejhlavacek říkal, že ve Snowflake ani Redshiftu se nequotuje, tak nevím.(?)

**Comment by Halama** [comment]
tohle je syntax error ve snflk, takže je to potřeba quotovat.
`To support case-sensitive identifiers, as well as allowing identifiers to start with special characters and use extended characters (including blank spaces), identifiers can be enclosed in double quotes.`

https://docs.snowflake.net/manuals/sql-reference/identifiers-syntax.html

**Comment by JakubMatejka** [comment]
Aha, tak já tam dával backticky

**Comment by Halama** [comment]
Aha tak to zkus s těma double quotes, to by mělo projít, jinak je to bug u nich.
 
Wtf. koukám že backtick se chová fakt divně 

```
CREATE TABLE "test" (`21_03_2018_57` VARCHAR NOT NULL);
```

založí  tabulku ve které je sloupec ``` `21_03_2018_57` ``` :) Bude to tím že tam nemá žádný speciální význam.

**Comment by ondrejhlavacek** [comment]
@JakubMatejka jestli jsem říkal, že Snowflake ani Redshift nequotují, tak jsem musel mít zatmění vesmíru, nebo jsem říkal, že nequotují backtickama :-)

**Comment by JakubMatejka** [comment]
No tak i to je možný. ;o) 

Closed by e7c589f
