### ISSUE TITLE
missing table in input mapping

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/sqldep-analyzer#3]
forked from https://github.com/keboola/transformation-bundle/issues/94

Řešení asi nejlepší přes #1 a injectnout chybu s chybějící tabulkou (a možná bych to do SQLdepu nakonec poslal i tak, ale nejsem si v tomhle tak stopro jistej).

**Comment by JakubMatejka** [comment]
Fixed by https://github.com/keboola/sqldep-analyzer/releases/tag/2.0.0

**Comment by ondrejhlavacek** [comment]
Dostal jsem hlášku 
```
Table out.c-main.view defined in input mapping of transformation 368746390 does not exist in Storage.
```

To ID transformace je tam navíc, je to číslo a nechci ho replacovat ve stringu, link na transformaci (pojmenovanou jménem, vygenerovanej UI) bude nad zprávou. `Table out.c-main.view defined in input mapping does not exist in Storage.` by mohlo stačit.

**Comment by ondrejhlavacek** [comment]
A ještě... Identifikátor `out.c-main.view` není jednoznačnej, potřebuju, aby v tom objektu byl název tabulky v DB (destination v input mappingu), podle toho už se to pozná.
```
    {
        "transformation": "368746390",
        "object": {
            "type": "table",
            "id": "out.c-main.view"
        },
        "message": "Table out.c-main.view defined in input mapping of transformation 368746390 does not exist in Storage."
    }
```
=> (cca)
```
    {
        "transformation": "368746390",
        "object": {
            "type": "table",
            "id": "user"
        },
        "message": "Table user defined in input mapping from out.c-main.view does not exist in Storage."
    }
```

(texty pak ještě poladím s Hankou a na to bych už snad zvládl poslat PR :-))

**Comment by ondrejhlavacek** [comment]
ještě furt dostávám

```
    {
        "transformation": "368746390",
        "object": {
            "type": "table",
            "id": "out.c-main.view"
        },
        "message": "Table view defined in input mapping as out.c-main.view does not exist in Storage."
    }
```
a potřeboval bych v `object.id` mít `destination` z input mappingu (v UI není id tabulky ze Storage unikátní)

**Comment by JakubMatejka** [comment]
Pardon, mám v tom už hokej, kde má být jaký id. ;o/  Ale tohle by mělo být ok, ne? `destination` je hned ve druhým slově
![sqldep-analyzer 2018-03-23 10-59-13](https://user-images.githubusercontent.com/215660/37823280-544f5380-2e89-11e8-978f-b21f3bf92813.png)

**Comment by ondrejhlavacek** [comment]
Jo, zpráva je v pohodě! Jen bych tenhle identifikátor potřebova dostat do `object.id`, bude tam link na input mapping a ten se musí orientovat podle jmen tabulek v databázi.

**Comment by ondrejhlavacek** [comment]
V tom předchozím commentu jsem měl typo, místo `user` tam mělo být `view` (komentář upravenej), pardon!

**Comment by JakubMatejka** [comment]
omg, jasně. Za chvíli to tam bude

**Comment by ondrejhlavacek** [comment]
Sepíšu všechny možný chybový stavy input mappingů a output mappingů někde pohromadě, ok?

**Comment by JakubMatejka** [comment]
Jo, to by bylo super :+1:

**Comment by JakubMatejka** [comment]
Tak už ;o)

**Comment by ondrejhlavacek** [comment]
Jo! :-) Je to tam :-)

![image](https://user-images.githubusercontent.com/497675/37825765-41347dc2-2e91-11e8-89b6-c739f3c12364.png)
