### ISSUE TITLE
Table {...} defined in output mapping of transformation {...} does not exist in Storage.

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/sqldep-analyzer#4]
```
Table out.c-sqldep-validation.out_users defined in output mapping of transformation 368746390 does not exist in Storage.
```

Tenhle error nedává smysl. To, že tabulka výstupu neexistuje je legitimní stav - třeba když setupuješ transformaci poprvý.

**Comment by JakubMatejka** [comment]
No ale jak mám potom sestavit sloupce do toho `CREATE TABLES AS SELECT`?

**Comment by ondrejhlavacek** [comment]
Nijak, v takovemhle případě tahle query nebude.
