### ISSUE TITLE
Input / Output Mapping Overview

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/sqldep-analyzer#5]
# 1) Input `in.c-ex-mysql.data` => `data`

## ✅ a) in.c-ex-mysql.data neexistuje 

https://connection.keboola.com/admin/projects/232/transformations/bucket/368746352/transformation/370685912

```
{
    "transformation": "1",
    "object": {
        "type": "input",
        "id": "data"
    },
    "message": "Table data defined in input mapping from in.c-ex-mysql.data does not exist in Storage."
}
```

![image](https://user-images.githubusercontent.com/497675/38546039-d93d0f58-3cab-11e8-8c45-ee353ed845bd.png)

## ✅ b) dvojitý rozdílný input mapping (in.c-ex-mysql.data => data, in.c-ex-mysql.data2 => data)

https://connection.keboola.com/admin/projects/232/transformations/bucket/368746352/transformation/370673690

#7, #12 

![image](https://user-images.githubusercontent.com/497675/38852454-3d2d8eac-421a-11e8-99e8-787005446203.png)

## ✅ c) dvojitý stejný input mapping (in.c-ex-mysql.data => data, in.c-ex-mysql.data => data)

https://connection.keboola.com/admin/projects/232/transformations/bucket/368746352/transformation/370680469

Nejde založit v UI v jedné transforamci, musí na to být 2 se závilostmi.

#8 

![image](https://user-images.githubusercontent.com/497675/38852490-62a96782-421a-11e8-93a6-dedd31fdb78c.png)

# 2) Output `data` => `out.c-data.data`

## ✅ a) out.c-data.data neexistuje

https://connection.keboola.com/admin/projects/232/transformations/bucket/368746352/transformation/370685724

Nevadí

## ✅  b) out.c-data.data má jinou strukturu

https://connection.keboola.com/admin/projects/232/transformations/bucket/368746352/transformation/370673690

```
{
    "transformation": "1",
    "object": {
        "type": "output",
        "id": "data"
    },
    "message": "Output mapping of data does not match the destiantion table in Storage out.c-data.data"
}
```

![image](https://user-images.githubusercontent.com/497675/38865643-b32d4722-423e-11e8-92a1-123ebc92c1a6.png)

#9 

## ✅ c) dvojitý output mapping (data => out.c-data.data + data => out.c-data.data2)

https://connection.keboola.com/admin/projects/232/transformations/bucket/368746352/transformation/370685316

Nevadí

## 🙈 d) duplicitní output mapping (data => out.c-data.data + data2 => out.c-data.data) do neexistující tabulky

https://connection.keboola.com/admin/projects/232/transformations/bucket/368746352/transformation/370687520

#10 

## ✅  e) duplicitní output mapping (data => out.c-data.data + data2 => out.c-data.data) do existující tabulky

https://connection.keboola.com/admin/projects/232/transformations/bucket/368746352/transformation/370691025

![image](https://user-images.githubusercontent.com/497675/38865665-c32f97f6-423e-11e8-96b9-54400068ee80.png)

**Comment by ondrejhlavacek** [comment]
Issues k jednotlivým bodům bych založil separátně. Tady jen přehled, prosím mrkni, jestli ti to dává smysl.

**Comment by ondrejhlavacek** [comment]
Budu udržovat popisek issue up-to-date.

**Comment by ondrejhlavacek** [comment]
Jakmile vytvořím nějakou transformaci v https://connection.keboola.com/admin/projects/232/transformations/bucket/368746352, tak už jí nebudu měnit, aby se to dalo znovu snadno otestovat.

**Comment by Halama** [comment]
Založil jsem nové issue na to na co jsem narazil. Vypadá to ale že se nic neduplikuje a tohle je celkově vyřešené?

**Comment by ondrejhlavacek** [comment]
Jo, tohle jsem všechno kontroloval, to můžem zavřít.
