### ISSUE TITLE
Duplicite Input Mapping (Different Tables)

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/sqldep-analyzer#7]
https://connection.keboola.com/admin/projects/232/transformations/bucket/368746352/transformation/370673690

Jde o situaci 1b) z https://github.com/keboola/sqldep-analyzer/issues/5

API vrátí že SQL je validní. 

Bylo by super, kdyby to řeklo, že existují dva input mappingy, který nesouhlasí, ale nevím, jak moc je to technicky složitý. transformace to uměj sofistikovaně mergovat (úplně zbytečně), takže bych řekl, že by to mohlo vyhodit chybu (patrně detekovanou u nás), že ze dvou tabulek se dělá jedna (a jednu z nich do SQLdepu neposílat, možná tu, co se založí v "pozdější" transformaci?)

**Comment by JakubMatejka** [comment]
A neměl by failovat spíš Sqldep, když se v něm vytváří dvě tabulky se stejným názvem?

**Comment by ondrejhlavacek** [comment]
Dobrá otázka, pošleš to na #3rd_sqldep?

**Comment by JakubMatejka** [comment]
Ok, tak měním `sqldep-dbdef:` na `CREATE TABLE`, SqlDep na tom vyfailuje (až to poladěj ;o)

**Comment by JakubMatejka** [comment]
Tak sláva
