### ISSUE TITLE
Output Mapping Does Not Match

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/sqldep-analyzer#9]
https://connection.keboola.com/admin/projects/232/transformations/bucket/368746352/transformation/369630788

2b) z #5 

API vrátí

```
    {
        "transformation": "369630788",
        "object": {
            "type": "output",
            "id": "out"
        },
        "message": "Problem with the source table for column \"firstname\" at line 1, column 14."
    }
```

 - tabulka `out` tam žádná není, jmenuje se `users`
 - chybová hláška nic neřekne, možná by to mohlo přechroustat a říct `Output mapping for table `users` does not match table `out.c-data.data` in Storage`? Ale to bych zatím nechal, když tam bude správnej identifikátor tabulky, tak to aspoň řekne název sloupce, to by mohlo bejt v pohodě! Jen bych asi vyhodil `at line 1, column 14` z hlášky bude tu super.

**Comment by JakubMatejka** [comment]
Tam se zas nějak dostalo id tabulky namísto jména a protože má v názvu tečky, tak se to blbě rozparsovalo (takže tam vlastně mělo být `out.c-users.users`, ale fixuju to na `users`). 

Jak by sis to přechroustávání představoval, to mám jako plošně nějakým regexem ze zpráv odstraňovat `at line \d+, column \d+`?

**Comment by ondrejhlavacek** [comment]
Máš nějakej jinej nápad? Line/column jsou irelevantní, protože ta query se sestavuje až u nás. Nebo by šel vyparsovat název sloupce a reportovat jen ten?

**Comment by ondrejhlavacek** [comment]
S těma chybama určitě můžou hejbat, celou tu validaci dělali kvůli nám, takže by to možná šlo nějak vylepšit a dát nám celou zprávu v nějaký čitelnější podobě :-) Zkusil by ses ho zeptat na Slacku (ať nedělám zbytečnou proxy)?
